//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Silverlight.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cotecna.Voc.Silverlight.Web.Resources.ServiceResource", typeof(ServiceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoC Iraq - Cerificate Approved.
        /// </summary>
        internal static string ApprovedCertificateSubject {
            get {
                return ResourceManager.GetString("ApprovedCertificateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Text.
        /// </summary>
        internal static string AutomaticText {
            get {
                return ResourceManager.GetString("AutomaticText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature not registered..
        /// </summary>
        internal static string CertificateApproveSignatureValidationError {
            get {
                return ResourceManager.GetString("CertificateApproveSignatureValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; field is empty..
        /// </summary>
        internal static string CertificateApproveValidationError {
            get {
                return ResourceManager.GetString("CertificateApproveValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; fields are empty..
        /// </summary>
        internal static string CertificateApproveValidationErrorPlural {
            get {
                return ResourceManager.GetString("CertificateApproveValidationErrorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Certificate Document..
        /// </summary>
        internal static string CertificateDocumentValidator {
            get {
                return ResourceManager.GetString("CertificateDocumentValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate document has an incorrect format, please upload a valid document..
        /// </summary>
        internal static string CertificateIncorrectFormat {
            get {
                return ResourceManager.GetString("CertificateIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Number.
        /// </summary>
        internal static string CertificateNumber {
            get {
                return ResourceManager.GetString("CertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be recalled while it is published..
        /// </summary>
        internal static string CertificateRecallPublishValidationError {
            get {
                return ResourceManager.GetString("CertificateRecallPublishValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Status.
        /// </summary>
        internal static string CertificateStatus {
            get {
                return ResourceManager.GetString("CertificateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not be unclosed while it is published..
        /// </summary>
        internal static string CertificateUnpublisPublishValidationError {
            get {
                return ResourceManager.GetString("CertificateUnpublisPublishValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COC.
        /// </summary>
        internal static string COC {
            get {
                return ResourceManager.GetString("COC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comdiv number.
        /// </summary>
        internal static string ComdivNumber {
            get {
                return ResourceManager.GetString("ComdivNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Exception error occurred while trying to delete the Certificate, please contact the administrator. Ex:.
        /// </summary>
        internal static string DeleteCertificateExeption {
            get {
                return ResourceManager.GetString("DeleteCertificateExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist.
        /// </summary>
        internal static string DeleteDocumentsFailMessage {
            get {
                return ResourceManager.GetString("DeleteDocumentsFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary Check Results.
        /// </summary>
        internal static string DocumentaryCheckResults {
            get {
                return ResourceManager.GetString("DocumentaryCheckResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be sent because there is a problem with the mail server. Please contact with your system administrator..
        /// </summary>
        internal static string EmailErrorMessage {
            get {
                return ResourceManager.GetString("EmailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Point.
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the certificate document (.pdf) to process recall action..
        /// </summary>
        internal static string FileOpenMessage {
            get {
                return ResourceManager.GetString("FileOpenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reference.
        /// </summary>
        internal static string FileReference {
            get {
                return ResourceManager.GetString("FileReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOB Value.
        /// </summary>
        internal static string FOBValue {
            get {
                return ResourceManager.GetString("FOBValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid border fees.
        /// </summary>
        internal static string Invoiced {
            get {
                return ResourceManager.GetString("Invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while trying to delete the Certificate, please contact the administrator..
        /// </summary>
        internal static string IOErrorMessage {
            get {
                return ResourceManager.GetString("IOErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An I/O error occurred while trying to delete the document, please contact the administrator..
        /// </summary>
        internal static string IOErrorMessageDocument {
            get {
                return ResourceManager.GetString("IOErrorMessageDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance Date.
        /// </summary>
        internal static string IssuanceDate {
            get {
                return ResourceManager.GetString("IssuanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance date from.
        /// </summary>
        internal static string IssuanceDateFrom {
            get {
                return ResourceManager.GetString("IssuanceDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance date to.
        /// </summary>
        internal static string IssuanceDateTo {
            get {
                return ResourceManager.GetString("IssuanceDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        internal static string Issued {
            get {
                return ResourceManager.GetString("Issued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification by.
        /// </summary>
        internal static string ModificationBy {
            get {
                return ResourceManager.GetString("ModificationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date.
        /// </summary>
        internal static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date from.
        /// </summary>
        internal static string ModificationDateFrom {
            get {
                return ResourceManager.GetString("ModificationDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date to.
        /// </summary>
        internal static string ModificationDateTo {
            get {
                return ResourceManager.GetString("ModificationDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Weight.
        /// </summary>
        internal static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoC Iraq - Certificate without border fees.
        /// </summary>
        internal static string NoFeesCertificate {
            get {
                return ResourceManager.GetString("NoFeesCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation message could not be sent because there is no issuers assigned to this office or the configuration is wrong..
        /// </summary>
        internal static string NonExistIssuersMessage {
            get {
                return ResourceManager.GetString("NonExistIssuersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation message could not be sent because there are no user in the border point.
        /// </summary>
        internal static string NotExistLOUsers {
            get {
                return ResourceManager.GetString("NotExistLOUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation message could not be sent because there is no coordinators assigned to this office or the configuration is wrong..
        /// </summary>
        internal static string NotExistsCoordinatorsMessage {
            get {
                return ResourceManager.GetString("NotExistsCoordinatorsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Invoiced&quot; field is empty..
        /// </summary>
        internal static string NotInvoiceMessage {
            get {
                return ResourceManager.GetString("NotInvoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a valid range.
        /// </summary>
        internal static string NotValidRange {
            get {
                return ResourceManager.GetString("NotValidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCR.
        /// </summary>
        internal static string NRC {
            get {
                return ResourceManager.GetString("NRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of trucks.
        /// </summary>
        internal static string NumberTrucks {
            get {
                return ResourceManager.GetString("NumberTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        internal static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Code.
        /// </summary>
        internal static string OfficeCode {
            get {
                return ResourceManager.GetString("OfficeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Name.
        /// </summary>
        internal static string OfficeName {
            get {
                return ResourceManager.GetString("OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Results.
        /// </summary>
        internal static string OverallResults {
            get {
                return ResourceManager.GetString("OverallResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Fees - USD.
        /// </summary>
        internal static string PaidFees {
            get {
                return ResourceManager.GetString("PaidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Check Results.
        /// </summary>
        internal static string PhysicalCheckResults {
            get {
                return ResourceManager.GetString("PhysicalCheckResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is already published..
        /// </summary>
        internal static string PublishValidationError {
            get {
                return ResourceManager.GetString("PublishValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This range already exits..
        /// </summary>
        internal static string RangeAlreadyExists {
            get {
                return ResourceManager.GetString("RangeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoC Iraq- Certificate rejected.
        /// </summary>
        internal static string RejectCertificateSubjectMessage {
            get {
                return ResourceManager.GetString("RejectCertificateSubjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release notes.
        /// </summary>
        internal static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remitted to.
        /// </summary>
        internal static string RemittedTo {
            get {
                return ResourceManager.GetString("RemittedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoC Iraq- Request for approval.
        /// </summary>
        internal static string RequestApprovalSubjectMessage {
            get {
                return ResourceManager.GetString("RequestApprovalSubjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RN Number.
        /// </summary>
        internal static string RNNumber {
            get {
                return ResourceManager.GetString("RNNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Document.
        /// </summary>
        internal static string SupportingDocument {
            get {
                return ResourceManager.GetString("SupportingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This certificate cannot be found in Comdiv, please verify the comdiv number..
        /// </summary>
        internal static string SyncCertificateNotFound {
            get {
                return ResourceManager.GetString("SyncCertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate type not exist in comdiv, please contact your system administrator..
        /// </summary>
        internal static string SyncCertificateTypeNotFound {
            get {
                return ResourceManager.GetString("SyncCertificateTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This certificate cannot be synchronized because there is no comdiv platform installed in the certificate&apos;s office..
        /// </summary>
        internal static string SyncComdivNotPossible {
            get {
                return ResourceManager.GetString("SyncComdivNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point not exist in comdiv, please contact your system administrator..
        /// </summary>
        internal static string SyncEntrypointNotFound {
            get {
                return ResourceManager.GetString("SyncEntrypointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fob value cannot be synchonized in comdiv, please contact your system administrator..
        /// </summary>
        internal static string SyncFOBValueNotFound {
            get {
                return ResourceManager.GetString("SyncFOBValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The synchronization with comdiv have not been performed because the configuration is wrong. Please contact with your system administrator..
        /// </summary>
        internal static string SyncGeneralProblem {
            get {
                return ResourceManager.GetString("SyncGeneralProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is already unpublished..
        /// </summary>
        internal static string UnpublishValidationError {
            get {
                return ResourceManager.GetString("UnpublishValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login.
        /// </summary>
        internal static string UserLogin {
            get {
                return ResourceManager.GetString("UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following problems have been found: {0}.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        internal static string WorkflowStatus {
            get {
                return ResourceManager.GetString("WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
