
GRANT SELECT ON dbo.[HEADER] TO AppVocIraq
GRANT SELECT ON dbo.[DICTIONARY] TO AppVocIraq
GRANT SELECT ON dbo.[COMPANY] TO AppVocIraq
GRANT SELECT ON dbo.[ADDRESS] TO AppVocIraq
GRANT SELECT ON dbo.[CONTACT] TO AppVocIraq

GRANT INSERT, SELECT, UPDATE ON dbo.[ITEM] TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[COC] TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[ITEMPOI] TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[COCITEM] TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[ITEMPOI] TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[COCITEM] TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[COCCORIGIN]  TO AppVocIraq
GRANT INSERT, SELECT, UPDATE ON dbo.[COCITEMCORIGIN]  TO AppVocIraq