//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION
    {
        public int ACT_ID { get; set; }
        public System.DateTime ACT_DATE { get; set; }
        public Nullable<int> ACT_LOGINID { get; set; }
        public string ACT_WKSTN { get; set; }
        public string ACT_TEXT { get; set; }
        public bool IS_DELETED_YN { get; set; }
    }
}
