//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public ADDRESS()
        {
            this.CONTACTs = new HashSet<CONTACT>();
            this.HEADERs = new HashSet<HEADER>();
            this.INVOICEs = new HashSet<INVOICE>();
            this.ITPs = new HashSet<ITP>();
        }
    
        public int ADD_ID { get; set; }
        public int COM_ID { get; set; }
        public string ADD_ADDRESS { get; set; }
        public string ADD_ZIP_CODE { get; set; }
        public string ADD_CITY { get; set; }
        public Nullable<int> ADD_COUNTRY_ID { get; set; }
        public Nullable<bool> ADD_NO_MORE_VALID_YN { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public Nullable<bool> ADD_MAILING_ADDRESS_YN { get; set; }
        public System.Guid rowguid { get; set; }
        public string ADD_ADDRESS_LOC { get; set; }
        public string ADD_ZIP_CODE_LOC { get; set; }
        public string ADD_CITY_LOC { get; set; }
    
        public virtual ICollection<CONTACT> CONTACTs { get; set; }
        public virtual ICollection<HEADER> HEADERs { get; set; }
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        public virtual ICollection<ITP> ITPs { get; set; }
        public virtual COMPANY COMPANY { get; set; }
    }
}
