//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARCHIVE
    {
        public int ARC_ID { get; set; }
        public Nullable<int> ARC_NO { get; set; }
        public Nullable<int> ARC_LOCATION_ID { get; set; }
        public Nullable<int> ARC_HDR_ID1 { get; set; }
        public Nullable<int> ARC_HDR_ID2 { get; set; }
        public Nullable<int> ARC_HDR_ID3 { get; set; }
        public Nullable<int> ARC_HDR_ID4 { get; set; }
        public Nullable<int> ARC_HDR_ID5 { get; set; }
        public Nullable<int> ARC_HDR_ID6 { get; set; }
        public Nullable<int> ARC_HDR_ID7 { get; set; }
        public Nullable<int> ARC_HDR_ID8 { get; set; }
        public Nullable<System.DateTime> ARC_VIEW_DATE { get; set; }
        public string ARC_VIEW_USR { get; set; }
        public string ARC_VIEW_WKSTN { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
    }
}
