//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class COC
    {
        public COC()
        {
            this.COCCORIGINs = new HashSet<COCCORIGIN>();
            this.COCITEMs = new HashSet<COCITEM>();
            this.ISSUEDCERTIFICATEs = new HashSet<ISSUEDCERTIFICATE>();
            this.ITEMFEEs = new HashSet<ITEMFEE>();
        }
    
        public int COC_ID { get; set; }
        public int ITM_ID { get; set; }
        public string COC_NUMBER { get; set; }
        public Nullable<int> COC_CERTIFICATETYPE { get; set; }
        public Nullable<System.DateTime> COC_ISSUING_DATE { get; set; }
        public Nullable<System.DateTime> COC_SHIPMENT_DATE { get; set; }
        public Nullable<int> COC_RESULT { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public Nullable<int> COC_ENTRYPOINT_ID { get; set; }
        public Nullable<decimal> COC_QUANTITY { get; set; }
        public Nullable<int> COC_CORIGIN { get; set; }
        public Nullable<int> COC_DEST_PORT { get; set; }
        public Nullable<int> COC_CSUPPLY { get; set; }
        public string COC_TEST_LAB_REF { get; set; }
        public string COC_INV_NUMBER { get; set; }
        public Nullable<System.DateTime> COC_INV_DATE { get; set; }
        public string COC_EFORMM_NUMBER { get; set; }
        public string COC_LETTER_CREDIT { get; set; }
        public string COC_REMARK { get; set; }
        public string COC_SEAL_NUMBER { get; set; }
        public string COC_CNT_NUMBER { get; set; }
        public string COC_DOC_NUMBER { get; set; }
        public string COC_SIGNEE { get; set; }
        public Nullable<bool> COC_IS_ON_WEB_YN { get; set; }
        public Nullable<bool> COC_TRANSMITTED_YN { get; set; }
        public string COC_SHIPPER { get; set; }
        public string COC_CARRIER { get; set; }
        public Nullable<System.DateTime> COC_SUBMITTED_DATE { get; set; }
        public Nullable<System.DateTime> COC_GENERATED_DATE { get; set; }
        public string COC_IMP_NAME { get; set; }
        public string COC_IMP_ADDRESS { get; set; }
        public string COC_IMP_TEL { get; set; }
        public string COC_IMP_FAX { get; set; }
        public string COC_IMP_EMAIL { get; set; }
        public System.Guid rowguid { get; set; }
        public string COC_NCR_REASON { get; set; }
        public bool COC_IS_EDITED_BY_COTECNA_YN { get; set; }
        public bool COC_INFO_TO_BE_SYNC_YN { get; set; }
        public Nullable<int> COC_ROUTE { get; set; }
        public bool COC_IS_SYNCWEB_YN { get; set; }
        public Nullable<bool> COC_INVOICED_YN { get; set; }
        public string COC_WEB_NUMBER { get; set; }
    
        public virtual ICollection<COCCORIGIN> COCCORIGINs { get; set; }
        public virtual ICollection<COCITEM> COCITEMs { get; set; }
        public virtual ICollection<ISSUEDCERTIFICATE> ISSUEDCERTIFICATEs { get; set; }
        public virtual ICollection<ITEMFEE> ITEMFEEs { get; set; }
    }
}
