//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class COCITEM
    {
        public int COI_ID { get; set; }
        public int COC_ID { get; set; }
        public Nullable<int> COI_NUMBER { get; set; }
        public Nullable<int> COI_HS_CODE_DCL { get; set; }
        public string COI_HS_CODE_DCL_CODE { get; set; }
        public Nullable<decimal> COI_QUANTITY { get; set; }
        public string COI_BRAND { get; set; }
        public string COI_MODEL { get; set; }
        public string COI_PRODUCT { get; set; }
        public Nullable<int> COI_CATEGORY { get; set; }
        public string COI_NOM_REF { get; set; }
        public string COI_REG_LIC_REF { get; set; }
        public Nullable<bool> IS_DELETED_YN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual COC COC { get; set; }
    }
}
