//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComdivEntities : DbContext
    {
        public ComdivEntities()
            : base("name=ComdivEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTION> ACTIONs { get; set; }
        public DbSet<ADDRESS> ADDRESSes { get; set; }
        public DbSet<ARCHIVE> ARCHIVEs { get; set; }
        public DbSet<BANKINFO> BANKINFOes { get; set; }
        public DbSet<COC> COCs { get; set; }
        public DbSet<COCCORIGIN> COCCORIGINs { get; set; }
        public DbSet<COCITEM> COCITEMs { get; set; }
        public DbSet<COMPANY> COMPANies { get; set; }
        public DbSet<CONTACT> CONTACTs { get; set; }
        public DbSet<COUNTER> COUNTERs { get; set; }
        public DbSet<COUNTRY> COUNTRies { get; set; }
        public DbSet<DICTIONARY> DICTIONARies { get; set; }
        public DbSet<DOCUMENT> DOCUMENTs { get; set; }
        public DbSet<ERROR> ERRORs { get; set; }
        public DbSet<HEADER> HEADERs { get; set; }
        public DbSet<HSCODE> HSCODEs { get; set; }
        public DbSet<HSCODE_DETAILDESCRIPTION> HSCODE_DETAILDESCRIPTION { get; set; }
        public DbSet<HSDETAIL> HSDETAILs { get; set; }
        public DbSet<INVITEM> INVITEMs { get; set; }
        public DbSet<INVOICE> INVOICEs { get; set; }
        public DbSet<INVOICEPAYMENT> INVOICEPAYMENTs { get; set; }
        public DbSet<ISSUEDCERTIFICATE> ISSUEDCERTIFICATEs { get; set; }
        public DbSet<ITEM> ITEMs { get; set; }
        public DbSet<ITEMCOST> ITEMCOSTs { get; set; }
        public DbSet<ITEMFEE> ITEMFEEs { get; set; }
        public DbSet<ITEMPOI> ITEMPOIs { get; set; }
        public DbSet<ITP> ITPs { get; set; }
        public DbSet<LABORATORYANALYSI> LABORATORYANALYSIS { get; set; }
        public DbSet<LOCATION> LOCATIONs { get; set; }
        public DbSet<OFFICECOUNTER> OFFICECOUNTERs { get; set; }
        public DbSet<OFFICEDICTIONARY> OFFICEDICTIONARies { get; set; }
        public DbSet<OFFICEPARAMETER> OFFICEPARAMETERs { get; set; }
        public DbSet<POD> PODs { get; set; }
        public DbSet<POI> POIs { get; set; }
        public DbSet<REFCODE> REFCODEs { get; set; }
        public DbSet<REMARK> REMARKs { get; set; }
        public DbSet<REQUEST> REQUESTs { get; set; }
        public DbSet<ROLE> ROLEs { get; set; }
        public DbSet<SEAL> SEALs { get; set; }
        public DbSet<SEAL_DATE> SEAL_DATE { get; set; }
        public DbSet<SECPAPER> SECPAPERs { get; set; }
        public DbSet<SIGNATURE> SIGNATUREs { get; set; }
        public DbSet<USR> USRs { get; set; }
        public DbSet<USRROLE> USRROLEs { get; set; }
        public DbSet<V_DICTIONARY> V_DICTIONARY { get; set; }
        public DbSet<V_EXRATE> V_EXRATE { get; set; }
        public DbSet<V_OFFICE> V_OFFICE { get; set; }
    }
}
