//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY
    {
        public COMPANY()
        {
            this.ADDRESSes = new HashSet<ADDRESS>();
            this.HEADERs = new HashSet<HEADER>();
            this.INVOICEs = new HashSet<INVOICE>();
            this.ITPs = new HashSet<ITP>();
            this.REMARKs = new HashSet<REMARK>();
        }
    
        public int COM_ID { get; set; }
        public string COM_NAME { get; set; }
        public string COM_NAME_LOC { get; set; }
        public Nullable<int> COM_CLI_TYPE_ID { get; set; }
        public string COM_VAT { get; set; }
        public Nullable<bool> COM_CLI_YN { get; set; }
        public Nullable<bool> COM_PAY_YN { get; set; }
        public Nullable<bool> COM_INSP_YN { get; set; }
        public Nullable<int> COM_GROUP_ID { get; set; }
        public Nullable<int> COM_PAYING_ID { get; set; }
        public string COM_PAYING_REF { get; set; }
        public Nullable<int> COM_PAYING_DELAY { get; set; }
        public string COM_CONTRACT_NAME { get; set; }
        public Nullable<int> COM_TYPE_ID { get; set; }
        public Nullable<int> COM_UNPAID_NB { get; set; }
        public Nullable<decimal> COM_UNPAID_AMOUNT { get; set; }
        public string COM_ACTION { get; set; }
        public string COM_RESULT { get; set; }
        public string COM_DECISION { get; set; }
        public Nullable<bool> COM_NO_MORE_VALID_YN { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public Nullable<int> OFF_ID { get; set; }
        public string COM_SHORT_NAME { get; set; }
        public string COM_OTHER_LEGAL_NUMBER { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<bool> PRINT_COM_NAME_LOC_YN { get; set; }
        public Nullable<bool> COM_SHIPPER_YN { get; set; }
        public Nullable<bool> COM_EXPORTER_YN { get; set; }
        public Nullable<bool> COM_NOMINATOR_YN { get; set; }
        public Nullable<bool> COM_TRADER_YN { get; set; }
        public Nullable<bool> COM_BUYER_YN { get; set; }
        public string NavisionId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<bool> COM_NETPRINCIPAL_YN { get; set; }
        public Nullable<bool> COM_LABORATORY_YN { get; set; }
        public Nullable<bool> COM_OTHERSUBCONTRACTOR_YN { get; set; }
        public Nullable<bool> COM_IMPORTER_YN { get; set; }
    
        public virtual ICollection<ADDRESS> ADDRESSes { get; set; }
        public virtual ICollection<HEADER> HEADERs { get; set; }
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        public virtual ICollection<ITP> ITPs { get; set; }
        public virtual ICollection<REMARK> REMARKs { get; set; }
    }
}
