//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRY
    {
        public int CountryId { get; set; }
        public string Name { get; set; }
        public string COMDIVCode { get; set; }
        public string SONCAPCode { get; set; }
    }
}
