//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENT
    {
        public int DOC_ID { get; set; }
        public int ITM_ID { get; set; }
        public Nullable<byte> DOC_NUMBER { get; set; }
        public Nullable<int> DOC_TITLE_ID { get; set; }
        public string DOC_OTH_TITLE { get; set; }
        public string DOC_NAME { get; set; }
        public string DOC_TYPE { get; set; }
        public bool DOC_SP_REQ { get; set; }
        public Nullable<decimal> DOC_SIZE { get; set; }
        public Nullable<bool> DOC_WEBRIGHTS_R { get; set; }
        public Nullable<bool> DOC_WEBRIGHTS_D { get; set; }
        public Nullable<bool> DOC_CERTIF_YN { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<bool> DOC_ADD_IN_INV_YN { get; set; }
        public Nullable<bool> DOC_INSPECTOR_DOCUMENT_YN { get; set; }
        public bool DOC_IS_ISSUED_CERTIFICATE_YN { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
