//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR
    {
        public int ERR_ID { get; set; }
        public Nullable<System.DateTime> ERR_DATE { get; set; }
        public string ERR_LOGINID { get; set; }
        public string ERR_WKSTN { get; set; }
        public string ERR_SOURCE { get; set; }
        public string ERR_MSG { get; set; }
        public bool IS_DELETED_YN { get; set; }
    }
}
