//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSCODE
    {
        public HSCODE()
        {
            this.HSDETAILs = new HashSet<HSDETAIL>();
        }
    
        public int HSC_ID { get; set; }
        public string HSC_CODE { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<int> CREATOR { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public Nullable<int> LASTKEYER { get; set; }
        public byte EXPORT_CODE { get; set; }
        public int EXPORT_OFF { get; set; }
        public Nullable<byte> LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime LASTKEY_DATEUTC { get; set; }
    
        public virtual ICollection<HSDETAIL> HSDETAILs { get; set; }
    }
}
