//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUEDCERTIFICATE
    {
        public int ISS_ID { get; set; }
        public int COC_ID { get; set; }
        public int ISS_TYPE { get; set; }
        public string ISS_NUMBER { get; set; }
        public Nullable<int> ISS_VERSION { get; set; }
        public Nullable<System.DateTime> ISS_ISSUING_DATE { get; set; }
        public Nullable<System.DateTime> ISS_EXPIRATION_DATE { get; set; }
        public Nullable<bool> ISS_SAME_MANUFACTURER_YN { get; set; }
        public Nullable<bool> ISS_SAME_EXPORTER_YN { get; set; }
        public Nullable<int> ISS_RESULT { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual COC COC { get; set; }
    }
}
