//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMCOST
    {
        public int ITC_ID { get; set; }
        public int ITM_ID { get; set; }
        public Nullable<int> ITF_ID { get; set; }
        public int ITC_NUMBER { get; set; }
        public int ITC_TYPE_ID { get; set; }
        public int ITC_DESC_ID { get; set; }
        public Nullable<int> ITC_BASIS_ID { get; set; }
        public Nullable<decimal> ITC_QUANTITY { get; set; }
        public Nullable<int> ITC_CURR_ID { get; set; }
        public Nullable<decimal> ITC_AMOUNT { get; set; }
        public Nullable<int> ITC_SUB_DESC_ID { get; set; }
        public string ITC_DESCRIPTION_REMARK { get; set; }
        public string ITC_BASIS_REMARK { get; set; }
        public Nullable<decimal> ITC_XRATE_CCURR_TO_USD { get; set; }
        public Nullable<decimal> ITC_DISCOUNT { get; set; }
        public Nullable<decimal> ITC_PROVISION { get; set; }
        public Nullable<decimal> ITC_CHARGED { get; set; }
        public Nullable<decimal> ITC_XRATE_TO_FEE { get; set; }
        public Nullable<decimal> ITC_EXRATE_COST_TO_USD { get; set; }
        public Nullable<decimal> ITC_EXRATE_COST_TO_CHF { get; set; }
        public Nullable<decimal> ITC_EXRATE_COST_TO_LOC { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public Nullable<bool> ITC_EXPORT_PS_YN { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<decimal> ITC_ExrateToTotalFeeCurrency { get; set; }
        public Nullable<int> ITP_INSP_NAME_ID { get; set; }
        public Nullable<int> POI_ID { get; set; }
        public Nullable<bool> InternalCostYN { get; set; }
        public Nullable<bool> ExternalCostYN { get; set; }
        public string ExternalInvoiceNumber { get; set; }
        public Nullable<System.DateTime> ExternalInvoiceDate { get; set; }
        public Nullable<decimal> ExternalInvoiceValue { get; set; }
    
        public virtual ITEM ITEM { get; set; }
        public virtual ITEMFEE ITEMFEE { get; set; }
    }
}
