//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public ITEM()
        {
            this.DOCUMENTs = new HashSet<DOCUMENT>();
            this.INVOICEs = new HashSet<INVOICE>();
            this.ITEMCOSTs = new HashSet<ITEMCOST>();
            this.ITEMFEEs = new HashSet<ITEMFEE>();
            this.ITPs = new HashSet<ITP>();
            this.REMARKs = new HashSet<REMARK>();
        }
    
        public int ITM_ID { get; set; }
        public Nullable<int> HDR_ID { get; set; }
        public Nullable<byte> ITM_NUMBER { get; set; }
        public string ITM_PRODUCT { get; set; }
        public Nullable<decimal> ITM_QTY { get; set; }
        public Nullable<decimal> ITM_QTY2 { get; set; }
        public Nullable<int> ITM_UNIT_ID { get; set; }
        public string ITM_PACKING { get; set; }
        public Nullable<int> ITM_CATEGORY_ID { get; set; }
        public Nullable<int> ITM_INSPTYPE_ID { get; set; }
        public Nullable<int> ITM_TRANSPTYPE_ID { get; set; }
        public string ITM_TRANSPORT { get; set; }
        public Nullable<System.DateTime> ITM_ETA1 { get; set; }
        public Nullable<System.DateTime> ITM_ETA2 { get; set; }
        public Nullable<int> ITM_CURR_ID { get; set; }
        public Nullable<decimal> ITM_VALUE { get; set; }
        public bool ITM_PSI_YN { get; set; }
        public Nullable<decimal> ITM_FEE_TOT_AMOUNT { get; set; }
        public Nullable<decimal> ITM_FEE_TOT_AMOUNT_REF { get; set; }
        public bool ITM_FEE_SUBJ1_SEL { get; set; }
        public bool ITM_FEE_SUBJ2_SEL { get; set; }
        public bool ITM_FEE_SUBJ3_SEL { get; set; }
        public string ITM_FEE_SUBJ3_TEXT { get; set; }
        public string ITM_FEE_CONCERN_TEXT { get; set; }
        public string ITM_FEE_TXT0_TEXT { get; set; }
        public bool ITM_FEE_TXT1_SEL { get; set; }
        public string ITM_FEE_TXT1_TEXT { get; set; }
        public bool ITM_FEE_TXT2_SEL { get; set; }
        public string ITM_FEE_TXT2_TEXT { get; set; }
        public bool ITM_FEE_PRN_ASPER { get; set; }
        public Nullable<bool> ITM_FEE_SHOW_YN { get; set; }
        public Nullable<decimal> ITM_COS_LAB_AMOUNT { get; set; }
        public Nullable<int> ITM_COS_COU_CURR_ID { get; set; }
        public Nullable<decimal> ITM_COS_TOT_AMOUNT { get; set; }
        public Nullable<decimal> ITM_COS_TOT_AMOUNT_REF { get; set; }
        public bool ITM_COS_SUBJ1_SEL { get; set; }
        public bool ITM_COS_SUBJ2_SEL { get; set; }
        public bool ITM_COS_SUBJ3_SEL { get; set; }
        public string ITM_COS_SUBJ3_TEXT { get; set; }
        public bool ITM_COS_TXT1_SEL { get; set; }
        public string ITM_COS_TXT1_TEXT { get; set; }
        public Nullable<byte> ITM_LAST_TAB { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public Nullable<int> ITM_PRODUCT_ID { get; set; }
        public Nullable<System.DateTime> ITM_OS_LAST_UPDATE_DATE { get; set; }
        public Nullable<int> ITM_OS_LAST_UPDATE_KEYER_ID { get; set; }
        public Nullable<decimal> ITM_FEE_COMM_PCT { get; set; }
        public Nullable<int> ITM_SUBCATEGORY_ID { get; set; }
        public Nullable<int> ITM_DESTINATION_ID { get; set; }
        public Nullable<bool> ITM_EXPORT_FEE_COMM_PCT_PS_YN { get; set; }
        public Nullable<System.DateTime> ITM_DEADLINE { get; set; }
        public System.Guid rowguid { get; set; }
        public bool ITM_FEE_TXT3_SEL { get; set; }
        public string ITM_FEE_TXT3_TEXT { get; set; }
        public bool ITM_FEE_TXT4_SEL { get; set; }
        public string ITM_FEE_TXT4_TEXT { get; set; }
        public string ITM_SHIPPER { get; set; }
        public Nullable<int> ITM_DESTINATION_PLACE_ID { get; set; }
        public Nullable<int> ITM_SUB_SUBCATEGORY_ID { get; set; }
        public Nullable<bool> ITM_COMPLETED_REPORTS_YN { get; set; }
        public Nullable<System.DateTime> ITM_COMPLETED_REPORTS_DATE { get; set; }
        public Nullable<int> TotalFeeCurrency { get; set; }
        public Nullable<int> ITM_SHIPPER_NAME_ID { get; set; }
        public Nullable<int> ITM_SHIPPER_ADD_ID { get; set; }
        public Nullable<int> ITM_SHIPPER_CONT_ID { get; set; }
        public Nullable<int> ITM_EXPORTER_NAME_ID { get; set; }
        public Nullable<int> ITM_EXPORTER_ADD_ID { get; set; }
        public Nullable<int> ITM_EXPORTER_CONT_ID { get; set; }
        public Nullable<int> ITM_NOMINATOR_NAME_ID { get; set; }
        public Nullable<int> ITM_NOMINATOR_ADD_ID { get; set; }
        public Nullable<int> ITM_NOMINATOR_CONT_ID { get; set; }
        public Nullable<int> ITM_TRADER_NAME_ID { get; set; }
        public Nullable<int> ITM_TRADER_ADD_ID { get; set; }
        public Nullable<int> ITM_TRADER_CONT_ID { get; set; }
        public Nullable<int> ITM_BUYER_NAME_ID { get; set; }
        public Nullable<int> ITM_BUYER_ADD_ID { get; set; }
        public Nullable<int> ITM_BUYER_CONT_ID { get; set; }
        public Nullable<int> ITM_PAY_NAME_ID { get; set; }
        public Nullable<int> ITM_PAY_ADD_ID { get; set; }
        public Nullable<int> ITM_PAY_CONT_ID { get; set; }
        public Nullable<int> ITM_NETPRINCIPAL_NAME_ID { get; set; }
        public Nullable<int> ITM_NETPRINCIPAL_ADD_ID { get; set; }
        public Nullable<int> ITM_NETPRINCIPAL_CONT_ID { get; set; }
        public string InvoiceNumber { get; set; }
        public string PartialNumber { get; set; }
        public string AgentReference { get; set; }
        public string ClientReference { get; set; }
        public Nullable<decimal> ITM_VOC_QTY { get; set; }
        public Nullable<decimal> ITM_VOC_UNIT_ID { get; set; }
        public Nullable<int> ITM_GMT_PLATFORM { get; set; }
    
        public virtual ICollection<DOCUMENT> DOCUMENTs { get; set; }
        public virtual HEADER HEADER { get; set; }
        public virtual ICollection<INVOICE> INVOICEs { get; set; }
        public virtual ICollection<ITEMCOST> ITEMCOSTs { get; set; }
        public virtual ICollection<ITEMFEE> ITEMFEEs { get; set; }
        public virtual ICollection<ITP> ITPs { get; set; }
        public virtual ICollection<REMARK> REMARKs { get; set; }
    }
}
