//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMPOI
    {
        public int IPO_ID { get; set; }
        public int ITM_ID { get; set; }
        public Nullable<int> POI_ID { get; set; }
        public Nullable<int> IPO_INSPAT_ID { get; set; }
        public string IPO_WHSE { get; set; }
        public Nullable<System.DateTime> IPO_NOM_DATE { get; set; }
        public Nullable<System.DateTime> IPO_SCHED_DATE { get; set; }
        public Nullable<System.DateTime> IPO_INSP_DATE { get; set; }
        public Nullable<System.DateTime> IPO_REP_RET_DATE { get; set; }
        public Nullable<System.DateTime> IPO_INSP_DATE_TO { get; set; }
        public Nullable<System.DateTime> IPO_FINAL_DOC_RECEIVED { get; set; }
        public Nullable<System.DateTime> IPO_FINAL_RPT_ISSUED { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
    }
}
