//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class LABORATORYANALYSI
    {
        public int LAA_ID { get; set; }
        public int ITM_ID { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD01 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD02 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD03 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD04 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD05 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD06 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD07 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD08 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD09 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD10 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD11 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD12 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD13 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD14 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD15 { get; set; }
        public Nullable<decimal> LAA_GROUP01_FIELD16 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD01 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD02 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD03 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD04 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD05 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD06 { get; set; }
        public Nullable<decimal> LAA_GROUP02_FIELD07 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD01 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD02 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD03 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD04 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD05 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD06 { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD07 { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public byte EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public byte LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public Nullable<decimal> LAA_GROUP03_FIELD08 { get; set; }
    }
}
