//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int LOC_ID { get; set; }
        public string LOC_NAME { get; set; }
        public string LOC_CODE { get; set; }
        public Nullable<bool> IS_DELETED_YN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<System.DateTime> LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
