//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUEST
    {
        public int REQ_ID { get; set; }
        public string REQ_NO { get; set; }
        public Nullable<int> REQ_OFFER_ID { get; set; }
        public byte REQ_ORIGIN { get; set; }
        public string REQ_COMPNAME { get; set; }
        public string REQ_FIRSTNAME { get; set; }
        public string REQ_LASTNAME { get; set; }
        public Nullable<System.DateTime> REQ_DATE { get; set; }
        public int REQ_COMP_COUN_ID { get; set; }
        public string REQ_TEL { get; set; }
        public string REQ_EMAIL { get; set; }
        public string REQ_INSPTYP { get; set; }
        public string REQ_PRODUCT { get; set; }
        public Nullable<decimal> REQ_QTY { get; set; }
        public string REQ_UNIT { get; set; }
        public string REQ_POI_CITY { get; set; }
        public int REQ_POI_COUN_ID { get; set; }
        public int REQ_DEST_COUN_ID { get; set; }
        public Nullable<bool> REQ_PSI_INSP { get; set; }
        public string REQ_RMK_TEXT { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string CREATOR { get; set; }
        public Nullable<int> CREATOR_ID { get; set; }
        public string CREA_WKSTN { get; set; }
        public Nullable<System.DateTime> LASTKEY_DATE { get; set; }
        public string LASTKEYER { get; set; }
        public Nullable<int> LASTKEYER_ID { get; set; }
        public string LASTKEY_WKSTN { get; set; }
        public Nullable<byte> EXPORT_CODE { get; set; }
        public Nullable<int> EXPORT_OFF { get; set; }
        public Nullable<byte> LASTEXPORT_CODE { get; set; }
        public Nullable<System.DateTime> LASTEXPORT_DATE { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
