//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Comdiv.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNATURE
    {
        public int SIG_ID { get; set; }
        public int USR_ID { get; set; }
        public string SIG_FILE_NAME { get; set; }
        public string SIG_DESCRIPTION { get; set; }
        public bool IS_DELETED_YN { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public Nullable<int> CREATOR { get; set; }
        public System.DateTime LASTKEY_DATE { get; set; }
        public Nullable<int> LASTKEYER { get; set; }
    }
}
