//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.FileAccess.Invoker.FileServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServiceReference.IFileAccessService")]
    public interface IFileAccessService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileAccessService/InvokeService", ReplyAction="http://tempuri.org/IFileAccessService/InvokeServiceResponse")]
        void InvokeService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileAccessService/InvokeService", ReplyAction="http://tempuri.org/IFileAccessService/InvokeServiceResponse")]
        System.Threading.Tasks.Task InvokeServiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileAccessServiceChannel : Cotecna.Voc.FileAccess.Invoker.FileServiceReference.IFileAccessService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileAccessServiceClient : System.ServiceModel.ClientBase<Cotecna.Voc.FileAccess.Invoker.FileServiceReference.IFileAccessService>, Cotecna.Voc.FileAccess.Invoker.FileServiceReference.IFileAccessService {
        
        public FileAccessServiceClient() {
        }
        
        public FileAccessServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileAccessServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileAccessServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileAccessServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InvokeService() {
            base.Channel.InvokeService();
        }
        
        public System.Threading.Tasks.Task InvokeServiceAsync() {
            return base.Channel.InvokeServiceAsync();
        }
    }
}
