//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    
    [Flags]
    public enum CertificateStatusEnum : byte
    {
        Conform = 1,
        NonConform = 2,
        Cancelled = 3,
        New = 0
    }
}
