//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificateTracking
    {
        public int CertificateTranckingId { get; set; }
        public int CertificateId { get; set; }
        public System.DateTime TrackingDate { get; set; }
        public string TrackingBy { get; set; }
        public TrackingStatusEnum TrackingStatus { get; set; }
        public string CreationBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ModficationBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual Certificate Certificate { get; set; }
    }
}
