//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.Documents = new HashSet<Document>();
            this.ReleaseNotes = new HashSet<ReleaseNote>();
            this.CertificateTrackings = new HashSet<CertificateTracking>();
        }
    
        public int CertificateId { get; set; }
        public string Sequential { get; set; }
        public WorkflowStatusEnum WorkflowStatusId { get; set; }
        public bool IsPublished { get; set; }
        public CertificateStatusEnum CertificateStatusId { get; set; }
        public Nullable<System.DateTime> IssuanceDate { get; set; }
        public Nullable<bool> IsInvoiced { get; set; }
        public string CreationBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> EntryPointId { get; set; }
        public Nullable<int> OfficeId { get; set; }
        public Nullable<System.DateTime> WorkflowStatusDate { get; set; }
        public string ModificationBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public string ApprovedBy { get; set; }
        public string ComdivNumber { get; set; }
        public Nullable<decimal> FOBValue { get; set; }
        public Nullable<bool> IsSynchronized { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual EntryPoint EntryPoint { get; set; }
        public virtual Office Office { get; set; }
        public virtual ICollection<ReleaseNote> ReleaseNotes { get; set; }
        public virtual ICollection<CertificateTracking> CertificateTrackings { get; set; }
    }
}
