//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryPoint
    {
        public EntryPoint()
        {
            this.Certificates = new HashSet<Certificate>();
            this.SecurityPapers = new HashSet<SecurityPaper>();
        }
    
        public int EntryPointId { get; set; }
        public string Name { get; set; }
        public string CreationBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ModificationBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<bool> IsLo { get; set; }
    
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<SecurityPaper> SecurityPapers { get; set; }
    }
}
