//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Certificates = new HashSet<Certificate>();
            this.LocalOffices = new HashSet<Office>();
        }
    
        public int OfficeId { get; set; }
        public string OfficeName { get; set; }
        public string OfficeCode { get; set; }
        public string CountryCode { get; set; }
        public string CreationBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDeleted { get; set; }
        public string ModificationBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public byte[] OfficeStamp { get; set; }
        public Nullable<OfficeTypeEnum> OfficeType { get; set; }
        public Nullable<int> RegionalOfficeId { get; set; }
        public string ServerName { get; set; }
        public string DatabaseName { get; set; }
    
        public virtual ICollection<Certificate> Certificates { get; set; }
        public virtual ICollection<Office> LocalOffices { get; set; }
        public virtual Office RegionalOffice { get; set; }
    }
}
