//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityPaper
    {
        public int SecurityPaperId { get; set; }
        public int EntryPointId { get; set; }
        public Nullable<int> ReleaseNoteId { get; set; }
        public string SecurityPaperNumber { get; set; }
        public SecurityPaperStatusEnum Status { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public string CreationBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModificationBy { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    
        public virtual EntryPoint EntryPoint { get; set; }
        public virtual ReleaseNote ReleaseNote { get; set; }
    }
}
