//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    
    [Flags]
    public enum ShipmentTypeEnum : byte
    {
        Air = 1,
        Maritime = 2,
        Land = 3,
        SeaLand = 4
    }
}
