//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    
    [Flags]
    public enum TrackingStatusEnum : byte
    {
        Created = 1,
        Requested = 2,
        Approved = 3,
        Rejected = 4,
        Ongoing = 5,
        Closed = 6,
        Published = 7,
        Unpublished = 8
    }
}
