//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotecna.Voc.Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VocEntities : DbContext
    {
        public VocEntities()
            : base("name=VocEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Document> Documents { get; set; }
        public DbSet<EntryPoint> EntryPoints { get; set; }
        public DbSet<Certificate> Certificates { get; set; }
        public DbSet<Office> Offices { get; set; }
        public DbSet<FileRequest> FileRequests { get; set; }
        public DbSet<ReleaseNote> ReleaseNotes { get; set; }
        public DbSet<SecurityPaper> SecurityPapers { get; set; }
        public DbSet<CertificateTracking> CertificateTrackings { get; set; }
    }
}
