//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string CancelStatus {
            get {
                return ResourceManager.GetString("CancelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha code.
        /// </summary>
        internal static string CaptchaCode {
            get {
                return ResourceManager.GetString("CaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the code shown above.
        /// </summary>
        internal static string CaptchaValue {
            get {
                return ResourceManager.GetString("CaptchaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string CertificateFile {
            get {
                return ResourceManager.GetString("CertificateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate list.
        /// </summary>
        internal static string CertificateList {
            get {
                return ResourceManager.GetString("CertificateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Number.
        /// </summary>
        internal static string CertificateNumber {
            get {
                return ResourceManager.GetString("CertificateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates.
        /// </summary>
        internal static string Certificates {
            get {
                return ResourceManager.GetString("Certificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Status.
        /// </summary>
        internal static string CertificateStatus {
            get {
                return ResourceManager.GetString("CertificateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string CertificateTitle {
            get {
                return ResourceManager.GetString("CertificateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Certificate.
        /// </summary>
        internal static string CertificateType {
            get {
                return ResourceManager.GetString("CertificateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully.
        /// </summary>
        internal static string ChangedPasswordConfirmationParagraph1 {
            get {
                return ResourceManager.GetString("ChangedPasswordConfirmationParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go to the login screen and log on with your username and your new password.
        /// </summary>
        internal static string ChangedPasswordConfirmationParagraph2 {
            get {
                return ResourceManager.GetString("ChangedPasswordConfirmationParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordButton {
            get {
                return ResourceManager.GetString("ChangePasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, please contact with the administrator.
        /// </summary>
        internal static string CommonErrorMessageAjax {
            get {
                return ResourceManager.GetString("CommonErrorMessageAjax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conform.
        /// </summary>
        internal static string CorformStatus {
            get {
                return ResourceManager.GetString("CorformStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailCertificate {
            get {
                return ResourceManager.GetString("DetailCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string DocumentCategory {
            get {
                return ResourceManager.GetString("DocumentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DocumentDescription {
            get {
                return ResourceManager.GetString("DocumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string DownloadCertificate {
            get {
                return ResourceManager.GetString("DownloadCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string EditingUser {
            get {
                return ResourceManager.GetString("EditingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write a valid email address.
        /// </summary>
        internal static string EmailFormatNotValid {
            get {
                return ResourceManager.GetString("EmailFormatNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Point.
        /// </summary>
        internal static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured in the execution of the action, please contact with the system administrator..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. The pdf file is not configured correctly for this certificate. Please contact with the administrator..
        /// </summary>
        internal static string ErrorPdfFile {
            get {
                return ResourceManager.GetString("ErrorPdfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error. The pdf file does not exist in the server. Please contact with the administrator..
        /// </summary>
        internal static string ErrorPdfFileNotExist {
            get {
                return ResourceManager.GetString("ErrorPdfFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error download.
        /// </summary>
        internal static string ErrorPdfTitle {
            get {
                return ResourceManager.GetString("ErrorPdfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportExcelButton {
            get {
                return ResourceManager.GetString("ExportExcelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is mandatory.
        /// </summary>
        internal static string FieldMandatoryValidation {
            get {
                return ResourceManager.GetString("FieldMandatoryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The captcha code isn&apos;t correct..
        /// </summary>
        internal static string ForgetPasswordCaptchaNotValid {
            get {
                return ResourceManager.GetString("ForgetPasswordCaptchaNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write an e-mail.
        /// </summary>
        internal static string ForgetPasswordEmailNotValid {
            get {
                return ResourceManager.GetString("ForgetPasswordEmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error changing the password.
        /// </summary>
        internal static string ForgetPasswordGeneralError {
            get {
                return ResourceManager.GetString("ForgetPasswordGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoC Iraq - Password has been changed sucessfully.
        /// </summary>
        internal static string ForgetPasswordSubjectConfirEmail {
            get {
                return ResourceManager.GetString("ForgetPasswordSubjectConfirEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoC Iraq – Password Recovery.
        /// </summary>
        internal static string ForgetPasswordSubjectEmail {
            get {
                return ResourceManager.GetString("ForgetPasswordSubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user was not found, please verify your information..
        /// </summary>
        internal static string ForgetPasswordUserNotFound {
            get {
                return ResourceManager.GetString("ForgetPasswordUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must contains at least one digit from 0-9 and one special symbols in the list &quot;@#$%[],+?~{}+.!&amp;*&apos;+/=^_`|-¡¿;&lt;&gt;°()\:&quot;.
        /// </summary>
        internal static string FormatPasswordValidation {
            get {
                return ResourceManager.GetString("FormatPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        internal static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to page:.
        /// </summary>
        internal static string GotoPage {
            get {
                return ResourceManager.GetString("GotoPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced.
        /// </summary>
        internal static string Invoiced {
            get {
                return ResourceManager.GetString("Invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance Date.
        /// </summary>
        internal static string IssuanceDate {
            get {
                return ResourceManager.GetString("IssuanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance Date From.
        /// </summary>
        internal static string IssuanceDateFrom {
            get {
                return ResourceManager.GetString("IssuanceDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuance Date To.
        /// </summary>
        internal static string IssuanceDateTo {
            get {
                return ResourceManager.GetString("IssuanceDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your search criteria:.
        /// </summary>
        internal static string LegendSearch {
            get {
                return ResourceManager.GetString("LegendSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged as {0}.
        /// </summary>
        internal static string LoggedAs {
            get {
                return ResourceManager.GetString("LoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is too large..
        /// </summary>
        internal static string MaxLegthPassword {
            get {
                return ResourceManager.GetString("MaxLegthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password length is too short, you have to write at least 8 characters.
        /// </summary>
        internal static string MinLegthPassword {
            get {
                return ResourceManager.GetString("MinLegthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The write the new password.
        /// </summary>
        internal static string NewPassRequired {
            get {
                return ResourceManager.GetString("NewPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Conform.
        /// </summary>
        internal static string NoCorformStatus {
            get {
                return ResourceManager.GetString("NoCorformStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password are not equals.
        /// </summary>
        internal static string NotIqualPasswordValidation {
            get {
                return ResourceManager.GetString("NotIqualPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} not valid.
        /// </summary>
        internal static string NotValidValue {
            get {
                return ResourceManager.GetString("NotValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user couldn´t be created.
        /// </summary>
        internal static string NoUserCreatedError {
            get {
                return ResourceManager.GetString("NoUserCreatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write the old password.
        /// </summary>
        internal static string OldPassRequired {
            get {
                return ResourceManager.GetString("OldPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is 1 error.
        /// </summary>
        internal static string OneError {
            get {
                return ResourceManager.GetString("OneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string PageCurrentPaginator {
            get {
                return ResourceManager.GetString("PageCurrentPaginator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your password.
        /// </summary>
        internal static string PasswordNotFilled {
            get {
                return ResourceManager.GetString("PasswordNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        internal static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Note.
        /// </summary>
        internal static string ReleaseNote {
            get {
                return ResourceManager.GetString("ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The re-write the new password.
        /// </summary>
        internal static string ReNewPassWordRequired {
            get {
                return ResourceManager.GetString("ReNewPassWordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordButton {
            get {
                return ResourceManager.GetString("ResetPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An e-mail has been sent to your e-mail address allowing you to reset your password..
        /// </summary>
        internal static string ResetPasswordConfirmationParagraph1 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may have to check your junk mail box for our message..
        /// </summary>
        internal static string ResetPasswordConfirmationParagraph2 {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to login.
        /// </summary>
        internal static string ReturnLogin {
            get {
                return ResourceManager.GetString("ReturnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Certificates.
        /// </summary>
        internal static string SearchCertificates {
            get {
                return ResourceManager.GetString("SearchCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Users.
        /// </summary>
        internal static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One Option.
        /// </summary>
        internal static string SelectOneOption {
            get {
                return ResourceManager.GetString("SelectOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must have 8 to 20 characters .
        /// </summary>
        internal static string ShortPasswordValidation {
            get {
                return ResourceManager.GetString("ShortPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} errors.
        /// </summary>
        internal static string SomeErrors {
            get {
                return ResourceManager.GetString("SomeErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field  is a mandatory field.
        /// </summary>
        internal static string SpecificMadatoryField {
            get {
                return ResourceManager.GetString("SpecificMadatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Document.
        /// </summary>
        internal static string SupportingDocument {
            get {
                return ResourceManager.GetString("SupportingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary password.
        /// </summary>
        internal static string TemporaryPassword {
            get {
                return ResourceManager.GetString("TemporaryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not active.
        /// </summary>
        internal static string UserInactive {
            get {
                return ResourceManager.GetString("UserInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string UserList {
            get {
                return ResourceManager.GetString("UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please write your email.
        /// </summary>
        internal static string UserNameNotFilled {
            get {
                return ResourceManager.GetString("UserNameNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        internal static string WorkflowStatus {
            get {
                return ResourceManager.GetString("WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email or password provided is incorrect.
        /// </summary>
        internal static string WrongLogin {
            get {
                return ResourceManager.GetString("WrongLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
